plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - /appendix/Appendix-Best-practices.md
  - /appendix/Appendix-Best-practices-Software.md
  - /appendix/Appendix-Best-practices-Hardware.md
  - /appendix/Appendix-Best-practices-Network.md
  
